# This file was auto-generated by Fern from our API Definition.

import enum


class VocodeEnvironment(enum.Enum):
    PRODUCTION = "https://api.vocode.dev"
    STAGING = "https://vocode-api-staging-5xerktxr4q-uc.a.run.app"
