# This file was auto-generated by Fern from our API Definition.

import typing
from ...types.agent_params import AgentParams

LinkPhoneNumberRequestInboundAgent = typing.Union[AgentParams, str, typing.Literal["default"]]
