# This file was auto-generated by Fern from our API Definition.

from .account_connection_page import AccountConnectionPage
from .account_connection_page_items_item import (
    AccountConnectionPageItemsItem,
    AccountConnectionPageItemsItem_AccountConnectionOpenai,
    AccountConnectionPageItemsItem_AccountConnectionTwilio,
)
from .account_connection_params_request import (
    AccountConnectionParamsRequest,
    AccountConnectionParamsRequest_AccountConnectionOpenai,
    AccountConnectionParamsRequest_AccountConnectionTwilio,
)
from .account_connection_response_model import (
    AccountConnectionResponseModel,
    AccountConnectionResponseModel_AccountConnectionOpenai,
    AccountConnectionResponseModel_AccountConnectionTwilio,
)
from .account_connection_update_params_request import (
    AccountConnectionUpdateParamsRequest,
    AccountConnectionUpdateParamsRequest_AccountConnectionOpenai,
    AccountConnectionUpdateParamsRequest_AccountConnectionTwilio,
)
from .action_page import ActionPage
from .action_page_items_item import (
    ActionPageItemsItem,
    ActionPageItemsItem_ActionAddToConference,
    ActionPageItemsItem_ActionDtmf,
    ActionPageItemsItem_ActionEndConversation,
    ActionPageItemsItem_ActionSetHold,
    ActionPageItemsItem_ActionTransferCall,
)
from .action_params_request import (
    ActionParamsRequest,
    ActionParamsRequest_ActionAddToConference,
    ActionParamsRequest_ActionDtmf,
    ActionParamsRequest_ActionEndConversation,
    ActionParamsRequest_ActionSetHold,
    ActionParamsRequest_ActionTransferCall,
)
from .action_response_model import (
    ActionResponseModel,
    ActionResponseModel_ActionAddToConference,
    ActionResponseModel_ActionDtmf,
    ActionResponseModel_ActionEndConversation,
    ActionResponseModel_ActionSetHold,
    ActionResponseModel_ActionTransferCall,
)
from .action_update_params_request import (
    ActionUpdateParamsRequest,
    ActionUpdateParamsRequest_ActionAddToConference,
    ActionUpdateParamsRequest_ActionDtmf,
    ActionUpdateParamsRequest_ActionEndConversation,
    ActionUpdateParamsRequest_ActionSetHold,
    ActionUpdateParamsRequest_ActionTransferCall,
)
from .add_to_conference_action import AddToConferenceAction
from .add_to_conference_action_action_trigger import (
    AddToConferenceActionActionTrigger,
    AddToConferenceActionActionTrigger_ActionTriggerFunctionCall,
    AddToConferenceActionActionTrigger_ActionTriggerPhraseBased,
)
from .add_to_conference_action_params import AddToConferenceActionParams
from .add_to_conference_action_params_action_trigger import (
    AddToConferenceActionParamsActionTrigger,
    AddToConferenceActionParamsActionTrigger_ActionTriggerFunctionCall,
    AddToConferenceActionParamsActionTrigger_ActionTriggerPhraseBased,
)
from .add_to_conference_action_update_params import AddToConferenceActionUpdateParams
from .add_to_conference_action_update_params_action_trigger import AddToConferenceActionUpdateParamsActionTrigger
from .add_to_conference_action_update_params_action_trigger_zero import (
    AddToConferenceActionUpdateParamsActionTriggerZero,
    AddToConferenceActionUpdateParamsActionTriggerZero_ActionTriggerFunctionCall,
    AddToConferenceActionUpdateParamsActionTriggerZero_ActionTriggerPhraseBased,
)
from .add_to_conference_action_update_params_config import AddToConferenceActionUpdateParamsConfig
from .add_to_conference_config import AddToConferenceConfig
from .agent import Agent
from .agent_actions_item import (
    AgentActionsItem,
    AgentActionsItem_ActionAddToConference,
    AgentActionsItem_ActionDtmf,
    AgentActionsItem_ActionEndConversation,
    AgentActionsItem_ActionSetHold,
    AgentActionsItem_ActionTransferCall,
)
from .agent_endpointing_sensitivity import AgentEndpointingSensitivity
from .agent_ivr_navigation_mode import AgentIvrNavigationMode
from .agent_page import AgentPage
from .agent_update_params import AgentUpdateParams
from .agent_update_params_actions import AgentUpdateParamsActions
from .agent_update_params_actions_item import AgentUpdateParamsActionsItem
from .agent_update_params_actions_item_one import (
    AgentUpdateParamsActionsItemOne,
    AgentUpdateParamsActionsItemOne_ActionAddToConference,
    AgentUpdateParamsActionsItemOne_ActionDtmf,
    AgentUpdateParamsActionsItemOne_ActionEndConversation,
    AgentUpdateParamsActionsItemOne_ActionSetHold,
    AgentUpdateParamsActionsItemOne_ActionTransferCall,
)
from .agent_update_params_ask_if_human_present_on_idle import AgentUpdateParamsAskIfHumanPresentOnIdle
from .agent_update_params_context_endpoint import AgentUpdateParamsContextEndpoint
from .agent_update_params_conversation_speed import AgentUpdateParamsConversationSpeed
from .agent_update_params_endpointing_sensitivity import AgentUpdateParamsEndpointingSensitivity
from .agent_update_params_initial_message import AgentUpdateParamsInitialMessage
from .agent_update_params_initial_message_delay import AgentUpdateParamsInitialMessageDelay
from .agent_update_params_interrupt_sensitivity import AgentUpdateParamsInterruptSensitivity
from .agent_update_params_ivr_navigation_mode import AgentUpdateParamsIvrNavigationMode
from .agent_update_params_language import AgentUpdateParamsLanguage
from .agent_update_params_noise_suppression import AgentUpdateParamsNoiseSuppression
from .agent_update_params_openai_account_connection import AgentUpdateParamsOpenaiAccountConnection
from .agent_update_params_openai_model_name_override import AgentUpdateParamsOpenaiModelNameOverride
from .agent_update_params_prompt import AgentUpdateParamsPrompt
from .agent_update_params_run_do_not_call_detection import AgentUpdateParamsRunDoNotCallDetection
from .agent_update_params_vector_database import AgentUpdateParamsVectorDatabase
from .agent_update_params_voice import AgentUpdateParamsVoice
from .agent_update_params_voice_one import (
    AgentUpdateParamsVoiceOne,
    AgentUpdateParamsVoiceOne_VoiceAzure,
    AgentUpdateParamsVoiceOne_VoiceElevenLabs,
    AgentUpdateParamsVoiceOne_VoicePlayHt,
    AgentUpdateParamsVoiceOne_VoiceRime,
)
from .agent_update_params_webhook import AgentUpdateParamsWebhook
from .agent_voice import (
    AgentVoice,
    AgentVoice_VoiceAzure,
    AgentVoice_VoiceElevenLabs,
    AgentVoice_VoicePlayHt,
    AgentVoice_VoiceRime,
)
from .azure_voice import AzureVoice
from .azure_voice_params import AzureVoiceParams
from .azure_voice_update_params import AzureVoiceUpdateParams
from .azure_voice_update_params_pitch import AzureVoiceUpdateParamsPitch
from .azure_voice_update_params_rate import AzureVoiceUpdateParamsRate
from .azure_voice_update_params_voice_name import AzureVoiceUpdateParamsVoiceName
from .buy_phone_number_request import BuyPhoneNumberRequest
from .buy_phone_number_request_telephony_provider import BuyPhoneNumberRequestTelephonyProvider
from .call import Call
from .call_human_detection_result import CallHumanDetectionResult
from .call_on_no_human_answer import CallOnNoHumanAnswer
from .call_page import CallPage
from .call_stage import CallStage
from .call_stage_outcome import CallStageOutcome
from .call_status import CallStatus
from .call_telephony_provider import CallTelephonyProvider
from .collect_field import CollectField
from .create_call_agent_params import CreateCallAgentParams
from .create_call_agent_params_actions_item import CreateCallAgentParamsActionsItem
from .create_call_agent_params_actions_item_one import (
    CreateCallAgentParamsActionsItemOne,
    CreateCallAgentParamsActionsItemOne_ActionAddToConference,
    CreateCallAgentParamsActionsItemOne_ActionDtmf,
    CreateCallAgentParamsActionsItemOne_ActionEndConversation,
    CreateCallAgentParamsActionsItemOne_ActionSetHold,
    CreateCallAgentParamsActionsItemOne_ActionTransferCall,
)
from .create_call_agent_params_endpointing_sensitivity import CreateCallAgentParamsEndpointingSensitivity
from .create_call_agent_params_ivr_navigation_mode import CreateCallAgentParamsIvrNavigationMode
from .create_call_agent_params_openai_account_connection import CreateCallAgentParamsOpenaiAccountConnection
from .create_call_agent_params_prompt import CreateCallAgentParamsPrompt
from .create_call_agent_params_vector_database import CreateCallAgentParamsVectorDatabase
from .create_call_agent_params_voice import CreateCallAgentParamsVoice
from .create_call_agent_params_voice_one import (
    CreateCallAgentParamsVoiceOne,
    CreateCallAgentParamsVoiceOne_VoiceAzure,
    CreateCallAgentParamsVoiceOne_VoiceElevenLabs,
    CreateCallAgentParamsVoiceOne_VoicePlayHt,
    CreateCallAgentParamsVoiceOne_VoiceRime,
)
from .create_call_agent_params_webhook import CreateCallAgentParamsWebhook
from .dtmf_action import DtmfAction
from .dtmf_action_action_trigger import (
    DtmfActionActionTrigger,
    DtmfActionActionTrigger_ActionTriggerFunctionCall,
    DtmfActionActionTrigger_ActionTriggerPhraseBased,
)
from .dtmf_action_params import DtmfActionParams
from .dtmf_action_params_action_trigger import (
    DtmfActionParamsActionTrigger,
    DtmfActionParamsActionTrigger_ActionTriggerFunctionCall,
    DtmfActionParamsActionTrigger_ActionTriggerPhraseBased,
)
from .dtmf_action_update_params import DtmfActionUpdateParams
from .dtmf_action_update_params_action_trigger import DtmfActionUpdateParamsActionTrigger
from .dtmf_action_update_params_action_trigger_zero import (
    DtmfActionUpdateParamsActionTriggerZero,
    DtmfActionUpdateParamsActionTriggerZero_ActionTriggerFunctionCall,
    DtmfActionUpdateParamsActionTriggerZero_ActionTriggerPhraseBased,
)
from .dtmf_action_update_params_config import DtmfActionUpdateParamsConfig
from .eleven_labs_voice import ElevenLabsVoice
from .eleven_labs_voice_params import ElevenLabsVoiceParams
from .eleven_labs_voice_update_params import ElevenLabsVoiceUpdateParams
from .eleven_labs_voice_update_params_api_key import ElevenLabsVoiceUpdateParamsApiKey
from .eleven_labs_voice_update_params_model_id import ElevenLabsVoiceUpdateParamsModelId
from .eleven_labs_voice_update_params_optimize_streaming_latency import (
    ElevenLabsVoiceUpdateParamsOptimizeStreamingLatency,
)
from .eleven_labs_voice_update_params_similarity_boost import ElevenLabsVoiceUpdateParamsSimilarityBoost
from .eleven_labs_voice_update_params_stability import ElevenLabsVoiceUpdateParamsStability
from .eleven_labs_voice_update_params_voice_id import ElevenLabsVoiceUpdateParamsVoiceId
from .empty_action_config import EmptyActionConfig
from .end_conversation_action import EndConversationAction
from .end_conversation_action_action_trigger import (
    EndConversationActionActionTrigger,
    EndConversationActionActionTrigger_ActionTriggerFunctionCall,
    EndConversationActionActionTrigger_ActionTriggerPhraseBased,
)
from .end_conversation_action_params import EndConversationActionParams
from .end_conversation_action_params_action_trigger import (
    EndConversationActionParamsActionTrigger,
    EndConversationActionParamsActionTrigger_ActionTriggerFunctionCall,
    EndConversationActionParamsActionTrigger_ActionTriggerPhraseBased,
)
from .end_conversation_action_update_params import EndConversationActionUpdateParams
from .end_conversation_action_update_params_action_trigger import EndConversationActionUpdateParamsActionTrigger
from .end_conversation_action_update_params_action_trigger_zero import (
    EndConversationActionUpdateParamsActionTriggerZero,
    EndConversationActionUpdateParamsActionTriggerZero_ActionTriggerFunctionCall,
    EndConversationActionUpdateParamsActionTriggerZero_ActionTriggerPhraseBased,
)
from .end_conversation_action_update_params_config import EndConversationActionUpdateParamsConfig
from .event_type import EventType
from .function_call_action_trigger import FunctionCallActionTrigger
from .function_call_action_trigger_config import FunctionCallActionTriggerConfig
from .http_method import HttpMethod
from .http_validation_error import HttpValidationError
from .interrupt_sensitivity import InterruptSensitivity
from .language import Language
from .normalized_agent import NormalizedAgent
from .normalized_agent_endpointing_sensitivity import NormalizedAgentEndpointingSensitivity
from .normalized_agent_ivr_navigation_mode import NormalizedAgentIvrNavigationMode
from .normalized_agent_openai_account_connection import NormalizedAgentOpenaiAccountConnection
from .normalized_agent_prompt import NormalizedAgentPrompt
from .normalized_agent_vector_database import NormalizedAgentVectorDatabase
from .normalized_call import NormalizedCall
from .normalized_call_human_detection_result import NormalizedCallHumanDetectionResult
from .normalized_call_on_no_human_answer import NormalizedCallOnNoHumanAnswer
from .normalized_call_stage import NormalizedCallStage
from .normalized_call_stage_outcome import NormalizedCallStageOutcome
from .normalized_call_telephony_account_connection import NormalizedCallTelephonyAccountConnection
from .normalized_call_telephony_provider import NormalizedCallTelephonyProvider
from .normalized_phone_number import NormalizedPhoneNumber
from .normalized_phone_number_telephony_account_connection import NormalizedPhoneNumberTelephonyAccountConnection
from .normalized_phone_number_telephony_provider import NormalizedPhoneNumberTelephonyProvider
from .normalized_prompt import NormalizedPrompt
from .open_ai_account_connection import OpenAiAccountConnection
from .open_ai_account_connection_params import OpenAiAccountConnectionParams
from .open_ai_account_connection_update_params import OpenAiAccountConnectionUpdateParams
from .open_ai_account_connection_update_params_credentials import OpenAiAccountConnectionUpdateParamsCredentials
from .open_ai_credentials import OpenAiCredentials
from .phone_number import PhoneNumber
from .phone_number_page import PhoneNumberPage
from .phone_number_telephony_provider import PhoneNumberTelephonyProvider
from .phrase_based_action_trigger import PhraseBasedActionTrigger
from .phrase_based_action_trigger_config import PhraseBasedActionTriggerConfig
from .phrase_trigger import PhraseTrigger
from .pinecone_vector_database import PineconeVectorDatabase
from .pinecone_vector_database_params import PineconeVectorDatabaseParams
from .pinecone_vector_database_update_params import PineconeVectorDatabaseUpdateParams
from .pinecone_vector_database_update_params_api_environment import PineconeVectorDatabaseUpdateParamsApiEnvironment
from .pinecone_vector_database_update_params_api_key import PineconeVectorDatabaseUpdateParamsApiKey
from .pinecone_vector_database_update_params_index import PineconeVectorDatabaseUpdateParamsIndex
from .plan_type import PlanType
from .play_ht_voice import PlayHtVoice
from .play_ht_voice_params import PlayHtVoiceParams
from .play_ht_voice_params_quality import PlayHtVoiceParamsQuality
from .play_ht_voice_params_version import PlayHtVoiceParamsVersion
from .play_ht_voice_quality import PlayHtVoiceQuality
from .play_ht_voice_update_params import PlayHtVoiceUpdateParams
from .play_ht_voice_update_params_api_key import PlayHtVoiceUpdateParamsApiKey
from .play_ht_voice_update_params_api_user_id import PlayHtVoiceUpdateParamsApiUserId
from .play_ht_voice_update_params_quality import PlayHtVoiceUpdateParamsQuality
from .play_ht_voice_update_params_speed import PlayHtVoiceUpdateParamsSpeed
from .play_ht_voice_update_params_temperature import PlayHtVoiceUpdateParamsTemperature
from .play_ht_voice_update_params_version import PlayHtVoiceUpdateParamsVersion
from .play_ht_voice_update_params_voice_id import PlayHtVoiceUpdateParamsVoiceId
from .play_ht_voice_version import PlayHtVoiceVersion
from .prompt import Prompt
from .prompt_page import PromptPage
from .prompt_params import PromptParams
from .prompt_params_prompt_template import PromptParamsPromptTemplate
from .prompt_template import PromptTemplate
from .prompt_update_params import PromptUpdateParams
from .prompt_update_params_collect_fields import PromptUpdateParamsCollectFields
from .prompt_update_params_content import PromptUpdateParamsContent
from .prompt_update_params_context_endpoint import PromptUpdateParamsContextEndpoint
from .prompt_update_params_prompt_template import PromptUpdateParamsPromptTemplate
from .rime_voice import RimeVoice
from .rime_voice_params import RimeVoiceParams
from .rime_voice_update_params import RimeVoiceUpdateParams
from .rime_voice_update_params_speaker import RimeVoiceUpdateParamsSpeaker
from .rime_voice_update_params_speed_alpha import RimeVoiceUpdateParamsSpeedAlpha
from .set_hold_action import SetHoldAction
from .set_hold_action_action_trigger import (
    SetHoldActionActionTrigger,
    SetHoldActionActionTrigger_ActionTriggerFunctionCall,
    SetHoldActionActionTrigger_ActionTriggerPhraseBased,
)
from .set_hold_action_params import SetHoldActionParams
from .set_hold_action_params_action_trigger import (
    SetHoldActionParamsActionTrigger,
    SetHoldActionParamsActionTrigger_ActionTriggerFunctionCall,
    SetHoldActionParamsActionTrigger_ActionTriggerPhraseBased,
)
from .set_hold_action_update_params import SetHoldActionUpdateParams
from .set_hold_action_update_params_action_trigger import SetHoldActionUpdateParamsActionTrigger
from .set_hold_action_update_params_action_trigger_zero import (
    SetHoldActionUpdateParamsActionTriggerZero,
    SetHoldActionUpdateParamsActionTriggerZero_ActionTriggerFunctionCall,
    SetHoldActionUpdateParamsActionTriggerZero_ActionTriggerPhraseBased,
)
from .set_hold_action_update_params_config import SetHoldActionUpdateParamsConfig
from .transfer_call_action import TransferCallAction
from .transfer_call_action_action_trigger import (
    TransferCallActionActionTrigger,
    TransferCallActionActionTrigger_ActionTriggerFunctionCall,
    TransferCallActionActionTrigger_ActionTriggerPhraseBased,
)
from .transfer_call_action_params import TransferCallActionParams
from .transfer_call_action_params_action_trigger import (
    TransferCallActionParamsActionTrigger,
    TransferCallActionParamsActionTrigger_ActionTriggerFunctionCall,
    TransferCallActionParamsActionTrigger_ActionTriggerPhraseBased,
)
from .transfer_call_action_update_params import TransferCallActionUpdateParams
from .transfer_call_action_update_params_action_trigger import TransferCallActionUpdateParamsActionTrigger
from .transfer_call_action_update_params_action_trigger_zero import (
    TransferCallActionUpdateParamsActionTriggerZero,
    TransferCallActionUpdateParamsActionTriggerZero_ActionTriggerFunctionCall,
    TransferCallActionUpdateParamsActionTriggerZero_ActionTriggerPhraseBased,
)
from .transfer_call_action_update_params_config import TransferCallActionUpdateParamsConfig
from .transfer_call_config import TransferCallConfig
from .twilio_account_connection import TwilioAccountConnection
from .twilio_account_connection_params import TwilioAccountConnectionParams
from .twilio_account_connection_update_params import TwilioAccountConnectionUpdateParams
from .twilio_account_connection_update_params_credentials import TwilioAccountConnectionUpdateParamsCredentials
from .twilio_credentials import TwilioCredentials
from .undefined import Undefined
from .usage import Usage
from .validation_error import ValidationError
from .validation_error_loc_item import ValidationErrorLocItem
from .vector_database_page import VectorDatabasePage
from .voice_page import VoicePage
from .voice_page_items_item import (
    VoicePageItemsItem,
    VoicePageItemsItem_VoiceAzure,
    VoicePageItemsItem_VoiceElevenLabs,
    VoicePageItemsItem_VoicePlayHt,
    VoicePageItemsItem_VoiceRime,
)
from .voice_params_request import (
    VoiceParamsRequest,
    VoiceParamsRequest_VoiceAzure,
    VoiceParamsRequest_VoiceElevenLabs,
    VoiceParamsRequest_VoicePlayHt,
    VoiceParamsRequest_VoiceRime,
)
from .voice_response_model import (
    VoiceResponseModel,
    VoiceResponseModel_VoiceAzure,
    VoiceResponseModel_VoiceElevenLabs,
    VoiceResponseModel_VoicePlayHt,
    VoiceResponseModel_VoiceRime,
)
from .voice_update_params_request import (
    VoiceUpdateParamsRequest,
    VoiceUpdateParamsRequest_VoiceAzure,
    VoiceUpdateParamsRequest_VoiceElevenLabs,
    VoiceUpdateParamsRequest_VoicePlayHt,
    VoiceUpdateParamsRequest_VoiceRime,
)
from .webhook import Webhook
from .webhook_page import WebhookPage
from .webhook_params import WebhookParams
from .webhook_update_params import WebhookUpdateParams
from .webhook_update_params_method import WebhookUpdateParamsMethod
from .webhook_update_params_subscriptions import WebhookUpdateParamsSubscriptions
from .webhook_update_params_url import WebhookUpdateParamsUrl

__all__ = [
    "AccountConnectionPage",
    "AccountConnectionPageItemsItem",
    "AccountConnectionPageItemsItem_AccountConnectionOpenai",
    "AccountConnectionPageItemsItem_AccountConnectionTwilio",
    "AccountConnectionParamsRequest",
    "AccountConnectionParamsRequest_AccountConnectionOpenai",
    "AccountConnectionParamsRequest_AccountConnectionTwilio",
    "AccountConnectionResponseModel",
    "AccountConnectionResponseModel_AccountConnectionOpenai",
    "AccountConnectionResponseModel_AccountConnectionTwilio",
    "AccountConnectionUpdateParamsRequest",
    "AccountConnectionUpdateParamsRequest_AccountConnectionOpenai",
    "AccountConnectionUpdateParamsRequest_AccountConnectionTwilio",
    "ActionPage",
    "ActionPageItemsItem",
    "ActionPageItemsItem_ActionAddToConference",
    "ActionPageItemsItem_ActionDtmf",
    "ActionPageItemsItem_ActionEndConversation",
    "ActionPageItemsItem_ActionSetHold",
    "ActionPageItemsItem_ActionTransferCall",
    "ActionParamsRequest",
    "ActionParamsRequest_ActionAddToConference",
    "ActionParamsRequest_ActionDtmf",
    "ActionParamsRequest_ActionEndConversation",
    "ActionParamsRequest_ActionSetHold",
    "ActionParamsRequest_ActionTransferCall",
    "ActionResponseModel",
    "ActionResponseModel_ActionAddToConference",
    "ActionResponseModel_ActionDtmf",
    "ActionResponseModel_ActionEndConversation",
    "ActionResponseModel_ActionSetHold",
    "ActionResponseModel_ActionTransferCall",
    "ActionUpdateParamsRequest",
    "ActionUpdateParamsRequest_ActionAddToConference",
    "ActionUpdateParamsRequest_ActionDtmf",
    "ActionUpdateParamsRequest_ActionEndConversation",
    "ActionUpdateParamsRequest_ActionSetHold",
    "ActionUpdateParamsRequest_ActionTransferCall",
    "AddToConferenceAction",
    "AddToConferenceActionActionTrigger",
    "AddToConferenceActionActionTrigger_ActionTriggerFunctionCall",
    "AddToConferenceActionActionTrigger_ActionTriggerPhraseBased",
    "AddToConferenceActionParams",
    "AddToConferenceActionParamsActionTrigger",
    "AddToConferenceActionParamsActionTrigger_ActionTriggerFunctionCall",
    "AddToConferenceActionParamsActionTrigger_ActionTriggerPhraseBased",
    "AddToConferenceActionUpdateParams",
    "AddToConferenceActionUpdateParamsActionTrigger",
    "AddToConferenceActionUpdateParamsActionTriggerZero",
    "AddToConferenceActionUpdateParamsActionTriggerZero_ActionTriggerFunctionCall",
    "AddToConferenceActionUpdateParamsActionTriggerZero_ActionTriggerPhraseBased",
    "AddToConferenceActionUpdateParamsConfig",
    "AddToConferenceConfig",
    "Agent",
    "AgentActionsItem",
    "AgentActionsItem_ActionAddToConference",
    "AgentActionsItem_ActionDtmf",
    "AgentActionsItem_ActionEndConversation",
    "AgentActionsItem_ActionSetHold",
    "AgentActionsItem_ActionTransferCall",
    "AgentEndpointingSensitivity",
    "AgentIvrNavigationMode",
    "AgentPage",
    "AgentUpdateParams",
    "AgentUpdateParamsActions",
    "AgentUpdateParamsActionsItem",
    "AgentUpdateParamsActionsItemOne",
    "AgentUpdateParamsActionsItemOne_ActionAddToConference",
    "AgentUpdateParamsActionsItemOne_ActionDtmf",
    "AgentUpdateParamsActionsItemOne_ActionEndConversation",
    "AgentUpdateParamsActionsItemOne_ActionSetHold",
    "AgentUpdateParamsActionsItemOne_ActionTransferCall",
    "AgentUpdateParamsAskIfHumanPresentOnIdle",
    "AgentUpdateParamsContextEndpoint",
    "AgentUpdateParamsConversationSpeed",
    "AgentUpdateParamsEndpointingSensitivity",
    "AgentUpdateParamsInitialMessage",
    "AgentUpdateParamsInitialMessageDelay",
    "AgentUpdateParamsInterruptSensitivity",
    "AgentUpdateParamsIvrNavigationMode",
    "AgentUpdateParamsLanguage",
    "AgentUpdateParamsNoiseSuppression",
    "AgentUpdateParamsOpenaiAccountConnection",
    "AgentUpdateParamsOpenaiModelNameOverride",
    "AgentUpdateParamsPrompt",
    "AgentUpdateParamsRunDoNotCallDetection",
    "AgentUpdateParamsVectorDatabase",
    "AgentUpdateParamsVoice",
    "AgentUpdateParamsVoiceOne",
    "AgentUpdateParamsVoiceOne_VoiceAzure",
    "AgentUpdateParamsVoiceOne_VoiceElevenLabs",
    "AgentUpdateParamsVoiceOne_VoicePlayHt",
    "AgentUpdateParamsVoiceOne_VoiceRime",
    "AgentUpdateParamsWebhook",
    "AgentVoice",
    "AgentVoice_VoiceAzure",
    "AgentVoice_VoiceElevenLabs",
    "AgentVoice_VoicePlayHt",
    "AgentVoice_VoiceRime",
    "AzureVoice",
    "AzureVoiceParams",
    "AzureVoiceUpdateParams",
    "AzureVoiceUpdateParamsPitch",
    "AzureVoiceUpdateParamsRate",
    "AzureVoiceUpdateParamsVoiceName",
    "BuyPhoneNumberRequest",
    "BuyPhoneNumberRequestTelephonyProvider",
    "Call",
    "CallHumanDetectionResult",
    "CallOnNoHumanAnswer",
    "CallPage",
    "CallStage",
    "CallStageOutcome",
    "CallStatus",
    "CallTelephonyProvider",
    "CollectField",
    "CreateCallAgentParams",
    "CreateCallAgentParamsActionsItem",
    "CreateCallAgentParamsActionsItemOne",
    "CreateCallAgentParamsActionsItemOne_ActionAddToConference",
    "CreateCallAgentParamsActionsItemOne_ActionDtmf",
    "CreateCallAgentParamsActionsItemOne_ActionEndConversation",
    "CreateCallAgentParamsActionsItemOne_ActionSetHold",
    "CreateCallAgentParamsActionsItemOne_ActionTransferCall",
    "CreateCallAgentParamsEndpointingSensitivity",
    "CreateCallAgentParamsIvrNavigationMode",
    "CreateCallAgentParamsOpenaiAccountConnection",
    "CreateCallAgentParamsPrompt",
    "CreateCallAgentParamsVectorDatabase",
    "CreateCallAgentParamsVoice",
    "CreateCallAgentParamsVoiceOne",
    "CreateCallAgentParamsVoiceOne_VoiceAzure",
    "CreateCallAgentParamsVoiceOne_VoiceElevenLabs",
    "CreateCallAgentParamsVoiceOne_VoicePlayHt",
    "CreateCallAgentParamsVoiceOne_VoiceRime",
    "CreateCallAgentParamsWebhook",
    "DtmfAction",
    "DtmfActionActionTrigger",
    "DtmfActionActionTrigger_ActionTriggerFunctionCall",
    "DtmfActionActionTrigger_ActionTriggerPhraseBased",
    "DtmfActionParams",
    "DtmfActionParamsActionTrigger",
    "DtmfActionParamsActionTrigger_ActionTriggerFunctionCall",
    "DtmfActionParamsActionTrigger_ActionTriggerPhraseBased",
    "DtmfActionUpdateParams",
    "DtmfActionUpdateParamsActionTrigger",
    "DtmfActionUpdateParamsActionTriggerZero",
    "DtmfActionUpdateParamsActionTriggerZero_ActionTriggerFunctionCall",
    "DtmfActionUpdateParamsActionTriggerZero_ActionTriggerPhraseBased",
    "DtmfActionUpdateParamsConfig",
    "ElevenLabsVoice",
    "ElevenLabsVoiceParams",
    "ElevenLabsVoiceUpdateParams",
    "ElevenLabsVoiceUpdateParamsApiKey",
    "ElevenLabsVoiceUpdateParamsModelId",
    "ElevenLabsVoiceUpdateParamsOptimizeStreamingLatency",
    "ElevenLabsVoiceUpdateParamsSimilarityBoost",
    "ElevenLabsVoiceUpdateParamsStability",
    "ElevenLabsVoiceUpdateParamsVoiceId",
    "EmptyActionConfig",
    "EndConversationAction",
    "EndConversationActionActionTrigger",
    "EndConversationActionActionTrigger_ActionTriggerFunctionCall",
    "EndConversationActionActionTrigger_ActionTriggerPhraseBased",
    "EndConversationActionParams",
    "EndConversationActionParamsActionTrigger",
    "EndConversationActionParamsActionTrigger_ActionTriggerFunctionCall",
    "EndConversationActionParamsActionTrigger_ActionTriggerPhraseBased",
    "EndConversationActionUpdateParams",
    "EndConversationActionUpdateParamsActionTrigger",
    "EndConversationActionUpdateParamsActionTriggerZero",
    "EndConversationActionUpdateParamsActionTriggerZero_ActionTriggerFunctionCall",
    "EndConversationActionUpdateParamsActionTriggerZero_ActionTriggerPhraseBased",
    "EndConversationActionUpdateParamsConfig",
    "EventType",
    "FunctionCallActionTrigger",
    "FunctionCallActionTriggerConfig",
    "HttpMethod",
    "HttpValidationError",
    "InterruptSensitivity",
    "Language",
    "NormalizedAgent",
    "NormalizedAgentEndpointingSensitivity",
    "NormalizedAgentIvrNavigationMode",
    "NormalizedAgentOpenaiAccountConnection",
    "NormalizedAgentPrompt",
    "NormalizedAgentVectorDatabase",
    "NormalizedCall",
    "NormalizedCallHumanDetectionResult",
    "NormalizedCallOnNoHumanAnswer",
    "NormalizedCallStage",
    "NormalizedCallStageOutcome",
    "NormalizedCallTelephonyAccountConnection",
    "NormalizedCallTelephonyProvider",
    "NormalizedPhoneNumber",
    "NormalizedPhoneNumberTelephonyAccountConnection",
    "NormalizedPhoneNumberTelephonyProvider",
    "NormalizedPrompt",
    "OpenAiAccountConnection",
    "OpenAiAccountConnectionParams",
    "OpenAiAccountConnectionUpdateParams",
    "OpenAiAccountConnectionUpdateParamsCredentials",
    "OpenAiCredentials",
    "PhoneNumber",
    "PhoneNumberPage",
    "PhoneNumberTelephonyProvider",
    "PhraseBasedActionTrigger",
    "PhraseBasedActionTriggerConfig",
    "PhraseTrigger",
    "PineconeVectorDatabase",
    "PineconeVectorDatabaseParams",
    "PineconeVectorDatabaseUpdateParams",
    "PineconeVectorDatabaseUpdateParamsApiEnvironment",
    "PineconeVectorDatabaseUpdateParamsApiKey",
    "PineconeVectorDatabaseUpdateParamsIndex",
    "PlanType",
    "PlayHtVoice",
    "PlayHtVoiceParams",
    "PlayHtVoiceParamsQuality",
    "PlayHtVoiceParamsVersion",
    "PlayHtVoiceQuality",
    "PlayHtVoiceUpdateParams",
    "PlayHtVoiceUpdateParamsApiKey",
    "PlayHtVoiceUpdateParamsApiUserId",
    "PlayHtVoiceUpdateParamsQuality",
    "PlayHtVoiceUpdateParamsSpeed",
    "PlayHtVoiceUpdateParamsTemperature",
    "PlayHtVoiceUpdateParamsVersion",
    "PlayHtVoiceUpdateParamsVoiceId",
    "PlayHtVoiceVersion",
    "Prompt",
    "PromptPage",
    "PromptParams",
    "PromptParamsPromptTemplate",
    "PromptTemplate",
    "PromptUpdateParams",
    "PromptUpdateParamsCollectFields",
    "PromptUpdateParamsContent",
    "PromptUpdateParamsContextEndpoint",
    "PromptUpdateParamsPromptTemplate",
    "RimeVoice",
    "RimeVoiceParams",
    "RimeVoiceUpdateParams",
    "RimeVoiceUpdateParamsSpeaker",
    "RimeVoiceUpdateParamsSpeedAlpha",
    "SetHoldAction",
    "SetHoldActionActionTrigger",
    "SetHoldActionActionTrigger_ActionTriggerFunctionCall",
    "SetHoldActionActionTrigger_ActionTriggerPhraseBased",
    "SetHoldActionParams",
    "SetHoldActionParamsActionTrigger",
    "SetHoldActionParamsActionTrigger_ActionTriggerFunctionCall",
    "SetHoldActionParamsActionTrigger_ActionTriggerPhraseBased",
    "SetHoldActionUpdateParams",
    "SetHoldActionUpdateParamsActionTrigger",
    "SetHoldActionUpdateParamsActionTriggerZero",
    "SetHoldActionUpdateParamsActionTriggerZero_ActionTriggerFunctionCall",
    "SetHoldActionUpdateParamsActionTriggerZero_ActionTriggerPhraseBased",
    "SetHoldActionUpdateParamsConfig",
    "TransferCallAction",
    "TransferCallActionActionTrigger",
    "TransferCallActionActionTrigger_ActionTriggerFunctionCall",
    "TransferCallActionActionTrigger_ActionTriggerPhraseBased",
    "TransferCallActionParams",
    "TransferCallActionParamsActionTrigger",
    "TransferCallActionParamsActionTrigger_ActionTriggerFunctionCall",
    "TransferCallActionParamsActionTrigger_ActionTriggerPhraseBased",
    "TransferCallActionUpdateParams",
    "TransferCallActionUpdateParamsActionTrigger",
    "TransferCallActionUpdateParamsActionTriggerZero",
    "TransferCallActionUpdateParamsActionTriggerZero_ActionTriggerFunctionCall",
    "TransferCallActionUpdateParamsActionTriggerZero_ActionTriggerPhraseBased",
    "TransferCallActionUpdateParamsConfig",
    "TransferCallConfig",
    "TwilioAccountConnection",
    "TwilioAccountConnectionParams",
    "TwilioAccountConnectionUpdateParams",
    "TwilioAccountConnectionUpdateParamsCredentials",
    "TwilioCredentials",
    "Undefined",
    "Usage",
    "ValidationError",
    "ValidationErrorLocItem",
    "VectorDatabasePage",
    "VoicePage",
    "VoicePageItemsItem",
    "VoicePageItemsItem_VoiceAzure",
    "VoicePageItemsItem_VoiceElevenLabs",
    "VoicePageItemsItem_VoicePlayHt",
    "VoicePageItemsItem_VoiceRime",
    "VoiceParamsRequest",
    "VoiceParamsRequest_VoiceAzure",
    "VoiceParamsRequest_VoiceElevenLabs",
    "VoiceParamsRequest_VoicePlayHt",
    "VoiceParamsRequest_VoiceRime",
    "VoiceResponseModel",
    "VoiceResponseModel_VoiceAzure",
    "VoiceResponseModel_VoiceElevenLabs",
    "VoiceResponseModel_VoicePlayHt",
    "VoiceResponseModel_VoiceRime",
    "VoiceUpdateParamsRequest",
    "VoiceUpdateParamsRequest_VoiceAzure",
    "VoiceUpdateParamsRequest_VoiceElevenLabs",
    "VoiceUpdateParamsRequest_VoicePlayHt",
    "VoiceUpdateParamsRequest_VoiceRime",
    "Webhook",
    "WebhookPage",
    "WebhookParams",
    "WebhookUpdateParams",
    "WebhookUpdateParamsMethod",
    "WebhookUpdateParamsSubscriptions",
    "WebhookUpdateParamsUrl",
]
