# This file was auto-generated by Fern from our API Definition.

import typing
from .open_ai_account_connection_params import OpenAiAccountConnectionParams
from .twilio_account_connection_params import TwilioAccountConnectionParams

AccountConnectionParamsRequest = typing.Union[OpenAiAccountConnectionParams, TwilioAccountConnectionParams]
