# This file was auto-generated by Fern from our API Definition.

import typing
from .open_ai_account_connection import OpenAiAccountConnection
from .twilio_account_connection import TwilioAccountConnection

AccountConnectionResponseModel = typing.Union[OpenAiAccountConnection, TwilioAccountConnection]
