# This file was auto-generated by Fern from our API Definition.

import typing
from .open_ai_account_connection_update_params import OpenAiAccountConnectionUpdateParams
from .twilio_account_connection_update_params import TwilioAccountConnectionUpdateParams

AccountConnectionUpdateParamsRequest = typing.Union[
    OpenAiAccountConnectionUpdateParams, TwilioAccountConnectionUpdateParams
]
