# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

from .add_to_conference_action_params import AddToConferenceActionParams
from .dtmf_action_params import DtmfActionParams
from .end_conversation_action_params import EndConversationActionParams
from .external_action_params import ExternalActionParams
from .set_hold_action_params import SetHoldActionParams
from .transfer_call_action_params import TransferCallActionParams


class ActionParamsRequest_ActionTransferCall(TransferCallActionParams):

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class ActionParamsRequest_ActionEndConversation(EndConversationActionParams):

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class ActionParamsRequest_ActionDtmf(DtmfActionParams):

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class ActionParamsRequest_ActionAddToConference(AddToConferenceActionParams):

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class ActionParamsRequest_ActionSetHold(SetHoldActionParams):

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class ActionParamsRequest_ActionExternal(ExternalActionParams):

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


ActionParamsRequest = typing.Union[
    TransferCallActionParams,
    EndConversationActionParams,
    DtmfActionParams,
    AddToConferenceActionParams,
    SetHoldActionParams,
    ExternalActionParams,
]
