# This file was auto-generated by Fern from our API Definition.

import typing
from .add_to_conference_action import AddToConferenceAction
from .dtmf_action import DtmfAction
from .end_conversation_action import EndConversationAction
from .external_action import ExternalAction
from .set_hold_action import SetHoldAction
from .transfer_call_action import TransferCallAction

ActionPageItemsItem = typing.Union[
    AddToConferenceAction, DtmfAction, EndConversationAction, ExternalAction, SetHoldAction, TransferCallAction
]
