# This file was auto-generated by Fern from our API Definition.

import typing

from .add_to_conference_action_update_params_action_trigger_zero import (
    AddToConferenceActionUpdateParamsActionTriggerZero,
)
from .undefined import Undefined

AddToConferenceActionUpdateParamsActionTrigger = typing.Union[
    AddToConferenceActionUpdateParamsActionTriggerZero, Undefined
]
