# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from .add_to_conference_action_update_params_config import AddToConferenceActionUpdateParamsConfig
from .add_to_conference_action_update_params_action_trigger import AddToConferenceActionUpdateParamsActionTrigger
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class AddToConferenceActionUpdateParams(UniversalBaseModel):
    type: typing.Literal["action_add_to_conference"] = "action_add_to_conference"
    config: typing.Optional[AddToConferenceActionUpdateParamsConfig] = None
    action_trigger: typing.Optional[AddToConferenceActionUpdateParamsActionTrigger] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
