# This file was auto-generated by Fern from our API Definition.

import typing

from .add_to_conference_config import AddToConferenceConfig
from .undefined import Undefined

AddToConferenceActionUpdateParamsConfig = typing.Union[AddToConferenceConfig, Undefined]
