# This file was auto-generated by Fern from our API Definition.

import typing

from .language import Language
from .undefined import Undefined

AgentUpdateParamsLanguage = typing.Union[Language, Undefined]
