# This file was auto-generated by Fern from our API Definition.

import typing

from .agent_update_params_actions_item_one import AgentUpdateParamsActionsItemOne

AgentUpdateParamsActionsItem = typing.Union[str, AgentUpdateParamsActionsItemOne]
