# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions

from .undefined import Undefined

AgentUpdateParamsIvrNavigationMode = typing.Union[
    typing_extensions.Literal["default"], typing_extensions.Literal["off"], Undefined
]
