# This file was auto-generated by Fern from our API Definition.

import typing
from .undefined import Undefined

AgentUpdateParamsIvrNavigationMode = typing.Union[typing.Literal["default"], typing.Literal["off"], Undefined]
