# This file was auto-generated by Fern from our API Definition.

import typing

from .agent_update_params_actions_item import AgentUpdateParamsActionsItem
from .undefined import Undefined

AgentUpdateParamsActions = typing.Union[typing.List[AgentUpdateParamsActionsItem], Undefined]
