# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import typing_extensions

from .dtmf_action_params import DtmfActionParams
from .end_conversation_action_params import EndConversationActionParams
from .transfer_call_action_params import TransferCallActionParams


class AgentParamsActionsItemOne_ActionTransferCall(TransferCallActionParams):
    type: typing_extensions.Literal["action_transfer_call"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class AgentParamsActionsItemOne_ActionEndConversation(EndConversationActionParams):
    type: typing_extensions.Literal["action_end_conversation"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class AgentParamsActionsItemOne_ActionDtmf(DtmfActionParams):
    type: typing_extensions.Literal["action_dtmf"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


AgentParamsActionsItemOne = typing.Union[
    AgentParamsActionsItemOne_ActionTransferCall,
    AgentParamsActionsItemOne_ActionEndConversation,
    AgentParamsActionsItemOne_ActionDtmf,
]
