# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from .agent_update_params_name import AgentUpdateParamsName
from .agent_update_params_prompt import AgentUpdateParamsPrompt
from .agent_update_params_language import AgentUpdateParamsLanguage
from .agent_update_params_actions import AgentUpdateParamsActions
from .agent_update_params_voice import AgentUpdateParamsVoice
from .agent_update_params_initial_message import AgentUpdateParamsInitialMessage
from .agent_update_params_webhook import AgentUpdateParamsWebhook
from .agent_update_params_vector_database import AgentUpdateParamsVectorDatabase
from .agent_update_params_interrupt_sensitivity import AgentUpdateParamsInterruptSensitivity
from .agent_update_params_context_endpoint import AgentUpdateParamsContextEndpoint
from .agent_update_params_noise_suppression import AgentUpdateParamsNoiseSuppression
from .agent_update_params_endpointing_sensitivity import AgentUpdateParamsEndpointingSensitivity
from .agent_update_params_ivr_navigation_mode import AgentUpdateParamsIvrNavigationMode
from .agent_update_params_conversation_speed import AgentUpdateParamsConversationSpeed
from .agent_update_params_initial_message_delay import AgentUpdateParamsInitialMessageDelay
from .agent_update_params_openai_model_name_override import AgentUpdateParamsOpenaiModelNameOverride
from .agent_update_params_ask_if_human_present_on_idle import AgentUpdateParamsAskIfHumanPresentOnIdle
from .agent_update_params_openai_account_connection import AgentUpdateParamsOpenaiAccountConnection
from .agent_update_params_run_do_not_call_detection import AgentUpdateParamsRunDoNotCallDetection
from .agent_update_params_llm_fallback import AgentUpdateParamsLlmFallback
from .agent_update_params_deepgram_keywords import AgentUpdateParamsDeepgramKeywords
from .agent_update_params_idle_time_seconds import AgentUpdateParamsIdleTimeSeconds
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class AgentUpdateParams(UniversalBaseModel):
    name: typing.Optional[AgentUpdateParamsName] = None
    prompt: typing.Optional[AgentUpdateParamsPrompt] = None
    language: typing.Optional[AgentUpdateParamsLanguage] = None
    actions: typing.Optional[AgentUpdateParamsActions] = None
    voice: typing.Optional[AgentUpdateParamsVoice] = None
    initial_message: typing.Optional[AgentUpdateParamsInitialMessage] = None
    webhook: typing.Optional[AgentUpdateParamsWebhook] = None
    vector_database: typing.Optional[AgentUpdateParamsVectorDatabase] = None
    interrupt_sensitivity: typing.Optional[AgentUpdateParamsInterruptSensitivity] = None
    context_endpoint: typing.Optional[AgentUpdateParamsContextEndpoint] = None
    noise_suppression: typing.Optional[AgentUpdateParamsNoiseSuppression] = None
    endpointing_sensitivity: typing.Optional[AgentUpdateParamsEndpointingSensitivity] = None
    ivr_navigation_mode: typing.Optional[AgentUpdateParamsIvrNavigationMode] = None
    conversation_speed: typing.Optional[AgentUpdateParamsConversationSpeed] = None
    initial_message_delay: typing.Optional[AgentUpdateParamsInitialMessageDelay] = None
    openai_model_name_override: typing.Optional[AgentUpdateParamsOpenaiModelNameOverride] = None
    ask_if_human_present_on_idle: typing.Optional[AgentUpdateParamsAskIfHumanPresentOnIdle] = None
    openai_account_connection: typing.Optional[AgentUpdateParamsOpenaiAccountConnection] = None
    run_do_not_call_detection: typing.Optional[AgentUpdateParamsRunDoNotCallDetection] = None
    llm_fallback: typing.Optional[AgentUpdateParamsLlmFallback] = None
    deepgram_keywords: typing.Optional[AgentUpdateParamsDeepgramKeywords] = None
    idle_time_seconds: typing.Optional[AgentUpdateParamsIdleTimeSeconds] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
