# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class AgentUpdateParamsEndpointingSensitivity(str, enum.Enum):
    AUTO = "auto"
    RELAXED = "relaxed"

    def visit(self, auto: typing.Callable[[], T_Result], relaxed: typing.Callable[[], T_Result]) -> T_Result:
        if self is AgentUpdateParamsEndpointingSensitivity.AUTO:
            return auto()
        if self is AgentUpdateParamsEndpointingSensitivity.RELAXED:
            return relaxed()
