# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

from .undefined import Undefined

AgentUpdateParamsEndpointingSensitivity = typing.Union[AgentUpdateParamsEndpointingSensitivity, Undefined]
