# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic

from ..core.datetime_utils import serialize_datetime
from .agent_update_params_actions import AgentUpdateParamsActions
from .agent_update_params_context_endpoint import AgentUpdateParamsContextEndpoint
from .agent_update_params_conversation_speed import AgentUpdateParamsConversationSpeed
from .agent_update_params_endpointing_sensitivity import AgentUpdateParamsEndpointingSensitivity
from .agent_update_params_initial_message import AgentUpdateParamsInitialMessage
from .agent_update_params_initial_message_delay import AgentUpdateParamsInitialMessageDelay
from .agent_update_params_interrupt_sensitivity import AgentUpdateParamsInterruptSensitivity
from .agent_update_params_ivr_navigation_mode import AgentUpdateParamsIvrNavigationMode
from .agent_update_params_language import AgentUpdateParamsLanguage
from .agent_update_params_noise_suppression import AgentUpdateParamsNoiseSuppression
from .agent_update_params_prompt import AgentUpdateParamsPrompt
from .agent_update_params_vector_database import AgentUpdateParamsVectorDatabase
from .agent_update_params_voice import AgentUpdateParamsVoice
from .agent_update_params_webhook import AgentUpdateParamsWebhook


class AgentUpdateParams(pydantic.BaseModel):
    prompt: typing.Optional[AgentUpdateParamsPrompt]
    language: typing.Optional[AgentUpdateParamsLanguage]
    actions: typing.Optional[AgentUpdateParamsActions]
    voice: typing.Optional[AgentUpdateParamsVoice]
    initial_message: typing.Optional[AgentUpdateParamsInitialMessage]
    webhook: typing.Optional[AgentUpdateParamsWebhook]
    vector_database: typing.Optional[AgentUpdateParamsVectorDatabase]
    interrupt_sensitivity: typing.Optional[AgentUpdateParamsInterruptSensitivity]
    context_endpoint: typing.Optional[AgentUpdateParamsContextEndpoint]
    noise_suppression: typing.Optional[AgentUpdateParamsNoiseSuppression]
    endpointing_sensitivity: typing.Optional[AgentUpdateParamsEndpointingSensitivity]
    ivr_navigation_mode: typing.Optional[AgentUpdateParamsIvrNavigationMode]
    conversation_speed: typing.Optional[AgentUpdateParamsConversationSpeed]
    initial_message_delay: typing.Optional[AgentUpdateParamsInitialMessageDelay]

    def json(self, **kwargs: typing.Any) -> str:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().json(**kwargs_with_defaults)

    def dict(self, **kwargs: typing.Any) -> typing.Dict[str, typing.Any]:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().dict(**kwargs_with_defaults)

    class Config:
        frozen = True
        smart_union = True
        json_encoders = {dt.datetime: serialize_datetime}
