# This file was auto-generated by Fern from our API Definition.

import typing

from .open_ai_account_connection import OpenAiAccountConnection
from .undefined import Undefined

AgentUpdateParamsOpenaiAccountConnection = typing.Union[OpenAiAccountConnection, str, Undefined]
