# This file was auto-generated by Fern from our API Definition.

import typing

from .dtmf_action_update_params import DtmfActionUpdateParams
from .end_conversation_action_update_params import EndConversationActionUpdateParams
from .transfer_call_action_update_params import TransferCallActionUpdateParams

AgentUpdateParamsActionsItem = typing.Union[
    str, TransferCallActionUpdateParams, EndConversationActionUpdateParams, DtmfActionUpdateParams
]
