# This file was auto-generated by Fern from our API Definition.

import typing

from .dtmf_action_params import DtmfActionParams
from .end_conversation_action_params import EndConversationActionParams

AgentParamsActionsItem = typing.Union[str, EndConversationActionParams, DtmfActionParams]
