# This file was auto-generated by Fern from our API Definition.

import typing
from .webhook_update_params import WebhookUpdateParams
from .undefined import Undefined

AgentUpdateParamsWebhook = typing.Union[str, WebhookUpdateParams, Undefined]
