# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import typing_extensions

from .dtmf_action_update_params import DtmfActionUpdateParams
from .end_conversation_action_update_params import EndConversationActionUpdateParams
from .transfer_call_action_update_params import TransferCallActionUpdateParams


class AgentUpdateParamsActionsItemOne_ActionTransferCall(TransferCallActionUpdateParams):
    type: typing_extensions.Literal["action_transfer_call"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class AgentUpdateParamsActionsItemOne_ActionEndConversation(EndConversationActionUpdateParams):
    type: typing_extensions.Literal["action_end_conversation"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class AgentUpdateParamsActionsItemOne_ActionDtmf(DtmfActionUpdateParams):
    type: typing_extensions.Literal["action_dtmf"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


AgentUpdateParamsActionsItemOne = typing.Union[
    AgentUpdateParamsActionsItemOne_ActionTransferCall,
    AgentUpdateParamsActionsItemOne_ActionEndConversation,
    AgentUpdateParamsActionsItemOne_ActionDtmf,
]
