# This file was auto-generated by Fern from our API Definition.

import typing

from .prompt_update_params import PromptUpdateParams
from .undefined import Undefined

AgentUpdateParamsPrompt = typing.Union[str, PromptUpdateParams, Undefined]
