# This file was auto-generated by Fern from our API Definition.

import typing

from .agent_update_params_actions_agent_update_params_actions_item import (
    AgentUpdateParamsActionsAgentUpdateParamsActionsItem,
)
from .undefined import Undefined

AgentUpdateParamsActions = typing.Union[typing.List[AgentUpdateParamsActionsAgentUpdateParamsActionsItem], Undefined]
