# This file was auto-generated by Fern from our API Definition.

import typing
from .add_to_conference_action_update_params import AddToConferenceActionUpdateParams
from .dtmf_action_update_params import DtmfActionUpdateParams
from .end_conversation_action_update_params import EndConversationActionUpdateParams
from .external_action_update_params import ExternalActionUpdateParams
from .set_hold_action_update_params import SetHoldActionUpdateParams
from .transfer_call_action_update_params import TransferCallActionUpdateParams

AgentUpdateParamsActionsItemOne = typing.Union[
    AddToConferenceActionUpdateParams,
    DtmfActionUpdateParams,
    EndConversationActionUpdateParams,
    ExternalActionUpdateParams,
    SetHoldActionUpdateParams,
    TransferCallActionUpdateParams,
]
