# This file was auto-generated by Fern from our API Definition.

import typing
from .internal_llm_fallback import InternalLlmFallback
from .undefined import Undefined

AgentUpdateParamsLlmFallback = typing.Union[InternalLlmFallback, Undefined]
