# This file was auto-generated by Fern from our API Definition.

import typing

from .pinecone_vector_database_update_params import PineconeVectorDatabaseUpdateParams
from .undefined import Undefined

AgentUpdateParamsVectorDatabase = typing.Union[str, PineconeVectorDatabaseUpdateParams, Undefined]
