# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from .azure_voice_update_params_voice_name import AzureVoiceUpdateParamsVoiceName
from .azure_voice_update_params_pitch import AzureVoiceUpdateParamsPitch
from .azure_voice_update_params_rate import AzureVoiceUpdateParamsRate
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class AzureVoiceUpdateParams(UniversalBaseModel):
    type: typing.Literal["voice_azure"] = "voice_azure"
    voice_name: typing.Optional[AzureVoiceUpdateParamsVoiceName] = None
    pitch: typing.Optional[AzureVoiceUpdateParamsPitch] = None
    rate: typing.Optional[AzureVoiceUpdateParamsRate] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
