# This file was auto-generated by Fern from our API Definition.

import typing

CallStage = typing.Union[typing.Literal["created", "picked_up", "transfer_started", "transfer_successful"], typing.Any]
