# This file was auto-generated by Fern from our API Definition.

import typing
from .twilio_telephony_metadata import TwilioTelephonyMetadata
from .vonage_telephony_metadata import VonageTelephonyMetadata

CallTelephonyMetadata = typing.Union[TwilioTelephonyMetadata, VonageTelephonyMetadata]
