# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class CollectFieldFieldType(str, enum.Enum):
    FIELD_TYPE_EMAIL = "field_type_email"
    FIELD_TYPE_ADDRESS = "field_type_address"

    def visit(
        self, field_type_email: typing.Callable[[], T_Result], field_type_address: typing.Callable[[], T_Result]
    ) -> T_Result:
        if self is CollectFieldFieldType.FIELD_TYPE_EMAIL:
            return field_type_email()
        if self is CollectFieldFieldType.FIELD_TYPE_ADDRESS:
            return field_type_address()
