# This file was auto-generated by Fern from our API Definition.

import typing

from .create_call_agent_params_actions_item_one import CreateCallAgentParamsActionsItemOne

CreateCallAgentParamsActionsItem = typing.Union[str, CreateCallAgentParamsActionsItemOne]
