# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import typing_extensions

from .azure_voice_params import AzureVoiceParams
from .eleven_labs_voice_params import ElevenLabsVoiceParams
from .play_ht_voice_params import PlayHtVoiceParams
from .rime_voice_params import RimeVoiceParams


class CreateCallAgentParamsVoiceOne_VoiceAzure(AzureVoiceParams):

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class CreateCallAgentParamsVoiceOne_VoiceRime(RimeVoiceParams):

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class CreateCallAgentParamsVoiceOne_VoiceElevenLabs(ElevenLabsVoiceParams):

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class CreateCallAgentParamsVoiceOne_VoicePlayHt(PlayHtVoiceParams):

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


CreateCallAgentParamsVoiceOne = typing.Union[
    AzureVoiceParams,
    RimeVoiceParams,
    ElevenLabsVoiceParams,
    PlayHtVoiceParams,
]
