# This file was auto-generated by Fern from our API Definition.

import typing

from .create_call_agent_params_voice_one import CreateCallAgentParamsVoiceOne

CreateCallAgentParamsVoice = typing.Union[str, CreateCallAgentParamsVoiceOne]
