# This file was auto-generated by Fern from our API Definition.

import typing

from .create_call_agent_params import CreateCallAgentParams

CreateCallRequestAgent = typing.Union[str, CreateCallAgentParams]
