# This file was auto-generated by Fern from our API Definition.

import typing
from .add_to_conference_action_params import AddToConferenceActionParams
from .dtmf_action_params import DtmfActionParams
from .end_conversation_action_params import EndConversationActionParams
from .external_action_params import ExternalActionParams
from .set_hold_action_params import SetHoldActionParams
from .transfer_call_action_params import TransferCallActionParams

CreateCallAgentParamsActionsItemOne = typing.Union[
    AddToConferenceActionParams,
    DtmfActionParams,
    EndConversationActionParams,
    ExternalActionParams,
    SetHoldActionParams,
    TransferCallActionParams,
]
