# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from .empty_action_config import EmptyActionConfig
from .function_call_action_trigger import FunctionCallActionTrigger
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class DtmfAction(UniversalBaseModel):
    id: str
    user_id: str
    type: typing.Literal["action_dtmf"] = "action_dtmf"
    config: typing.Optional[EmptyActionConfig] = None
    action_trigger: typing.Optional[FunctionCallActionTrigger] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
