# This file was auto-generated by Fern from our API Definition.

import typing

from .empty_action_config import EmptyActionConfig
from .undefined import Undefined

DtmfActionUpdateParamsConfig = typing.Union[EmptyActionConfig, Undefined]
