# This file was auto-generated by Fern from our API Definition.

import typing
from .function_call_action_trigger import FunctionCallActionTrigger
from .phrase_based_action_trigger_output import PhraseBasedActionTriggerOutput

EndConversationActionActionTrigger = typing.Union[FunctionCallActionTrigger, PhraseBasedActionTriggerOutput]
