# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from .end_conversation_action_update_params_config import EndConversationActionUpdateParamsConfig
from .end_conversation_action_update_params_action_trigger import EndConversationActionUpdateParamsActionTrigger
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class EndConversationActionUpdateParams(UniversalBaseModel):
    type: typing.Literal["action_end_conversation"] = "action_end_conversation"
    config: typing.Optional[EndConversationActionUpdateParamsConfig] = None
    action_trigger: typing.Optional[EndConversationActionUpdateParamsActionTrigger] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
