# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import typing_extensions

from .function_call_action_trigger import FunctionCallActionTrigger
from .phrase_based_action_trigger import PhraseBasedActionTrigger


class EndConversationActionActionTrigger_ActionTriggerFunctionCall(FunctionCallActionTrigger):
    type: typing_extensions.Literal["action_trigger_function_call"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class EndConversationActionActionTrigger_ActionTriggerPhraseBased(PhraseBasedActionTrigger):
    type: typing_extensions.Literal["action_trigger_phrase_based"]

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


EndConversationActionActionTrigger = typing.Union[
    EndConversationActionActionTrigger_ActionTriggerFunctionCall,
    EndConversationActionActionTrigger_ActionTriggerPhraseBased,
]
