# This file was auto-generated by Fern from our API Definition.

import typing

from .end_conversation_action_update_params_action_trigger_zero import (
    EndConversationActionUpdateParamsActionTriggerZero,
)
from .undefined import Undefined

EndConversationActionUpdateParamsActionTrigger = typing.Union[
    EndConversationActionUpdateParamsActionTriggerZero, Undefined
]
