# This file was auto-generated by Fern from our API Definition.

import typing

from .action_config import ActionConfig
from .undefined import Undefined

EndConversationActionUpdateParamsConfig = typing.Union[ActionConfig, Undefined]
