# This file was auto-generated by Fern from our API Definition.

import typing

EventType = typing.Union[
    typing.Literal[
        "event_message",
        "event_action",
        "event_phone_call_connected",
        "event_phone_call_ended",
        "event_phone_call_did_not_connect",
        "event_transcript",
        "event_recording",
        "event_human_detection",
    ],
    typing.Any,
]
