# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from .external_action_update_params_config import ExternalActionUpdateParamsConfig
from .external_action_update_params_action_trigger import ExternalActionUpdateParamsActionTrigger
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class ExternalActionUpdateParams(UniversalBaseModel):
    type: typing.Literal["action_external"] = "action_external"
    config: typing.Optional[ExternalActionUpdateParamsConfig] = None
    action_trigger: typing.Optional[ExternalActionUpdateParamsActionTrigger] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
