# This file was auto-generated by Fern from our API Definition.

import typing

from .external_action_update_params_action_trigger_zero import ExternalActionUpdateParamsActionTriggerZero
from .undefined import Undefined

ExternalActionUpdateParamsActionTrigger = typing.Union[ExternalActionUpdateParamsActionTriggerZero, Undefined]
