# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class Language(str, enum.Enum):
    """
    An enumeration.
    """

    EN = "en"
    ES = "es"
    DE = "de"

    def visit(
        self, en: typing.Callable[[], T_Result], es: typing.Callable[[], T_Result], de: typing.Callable[[], T_Result]
    ) -> T_Result:
        if self is Language.EN:
            return en()
        if self is Language.ES:
            return es()
        if self is Language.DE:
            return de()
