# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class NormalizedCallStageOutcome(str, enum.Enum):
    HUMAN_UNANSWERED = "human_unanswered"
    HUMAN_DISCONNECTED = "human_disconnected"
    BOT_DISCONNECTED = "bot_disconnected"
    TRANSFER_UNANSWERED = "transfer_unanswered"
    TRANSFER_DISCONNECTED = "transfer_disconnected"

    def visit(
        self,
        human_unanswered: typing.Callable[[], T_Result],
        human_disconnected: typing.Callable[[], T_Result],
        bot_disconnected: typing.Callable[[], T_Result],
        transfer_unanswered: typing.Callable[[], T_Result],
        transfer_disconnected: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is NormalizedCallStageOutcome.HUMAN_UNANSWERED:
            return human_unanswered()
        if self is NormalizedCallStageOutcome.HUMAN_DISCONNECTED:
            return human_disconnected()
        if self is NormalizedCallStageOutcome.BOT_DISCONNECTED:
            return bot_disconnected()
        if self is NormalizedCallStageOutcome.TRANSFER_UNANSWERED:
            return transfer_unanswered()
        if self is NormalizedCallStageOutcome.TRANSFER_DISCONNECTED:
            return transfer_disconnected()
