# This file was auto-generated by Fern from our API Definition.

import typing

NormalizedCallStage = typing.Union[
    typing.Literal["created", "picked_up", "transfer_started", "transfer_successful"], typing.Any
]
