# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ..core.datetime_utils import serialize_datetime
from .normalized_phone_number_telephony_account_connection import NormalizedPhoneNumberTelephonyAccountConnection
from .normalized_phone_number_telephony_provider import NormalizedPhoneNumberTelephonyProvider

try:
    import pydantic.v1 as pydantic  # type: ignore
except ImportError:
    import pydantic  # type: ignore


class NormalizedPhoneNumber(pydantic.BaseModel):
    id: str
    user_id: str
    active: typing.Optional[bool]
    label: typing.Optional[str]
    inbound_agent: str
    outbound_only: typing.Optional[bool]
    example_context: typing.Optional[typing.Dict[str, str]]
    number: str
    telephony_provider: typing.Optional[NormalizedPhoneNumberTelephonyProvider]
    telephony_account_connection: typing.Optional[NormalizedPhoneNumberTelephonyAccountConnection]

    def json(self, **kwargs: typing.Any) -> str:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().json(**kwargs_with_defaults)

    def dict(self, **kwargs: typing.Any) -> typing.Dict[str, typing.Any]:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().dict(**kwargs_with_defaults)

    class Config:
        frozen = True
        smart_union = True
        json_encoders = {dt.datetime: serialize_datetime}
