# This file was auto-generated by Fern from our API Definition.

import typing

from .twilio_account_connection import TwilioAccountConnection

NormalizedPhoneNumberTelephonyAccountConnection = typing.Union[str, TwilioAccountConnection]
