# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from .call_status import CallStatus
from .normalized_call_human_detection_result import NormalizedCallHumanDetectionResult
from .normalized_call_stage import NormalizedCallStage
from .normalized_call_stage_outcome import NormalizedCallStageOutcome
from .normalized_call_telephony_metadata import NormalizedCallTelephonyMetadata
from .normalized_call_telephony_provider import NormalizedCallTelephonyProvider
from .normalized_call_on_no_human_answer import NormalizedCallOnNoHumanAnswer
from .normalized_call_telephony_account_connection import NormalizedCallTelephonyAccountConnection
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class NormalizedCall(UniversalBaseModel):
    id: str
    user_id: str
    status: typing.Optional[CallStatus] = None
    error_message: typing.Optional[str] = None
    recording_available: typing.Optional[bool] = None
    transcript: typing.Optional[str] = None
    human_detection_result: typing.Optional[NormalizedCallHumanDetectionResult] = None
    do_not_call_result: typing.Optional[bool] = None
    telephony_id: typing.Optional[str] = None
    stage: typing.Optional[NormalizedCallStage] = None
    stage_outcome: typing.Optional[NormalizedCallStageOutcome] = None
    telephony_metadata: typing.Optional[NormalizedCallTelephonyMetadata] = None
    start_time: typing.Optional[float] = None
    end_time: typing.Optional[float] = None
    to_number: str
    from_number: str
    agent: str
    telephony_provider: NormalizedCallTelephonyProvider
    agent_phone_number: str
    hipaa_compliant: typing.Optional[bool] = None
    on_no_human_answer: typing.Optional[NormalizedCallOnNoHumanAnswer] = None
    context: typing.Optional[typing.Dict[str, typing.Optional[str]]] = None
    run_do_not_call_detection: typing.Optional[bool] = None
    telephony_account_connection: typing.Optional[NormalizedCallTelephonyAccountConnection] = None
    telephony_params: typing.Optional[typing.Dict[str, typing.Optional[str]]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
