# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
from .open_ai_credentials import OpenAiCredentials
import typing
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class OpenAiAccountConnectionParams(UniversalBaseModel):
    credentials: OpenAiCredentials
    type: typing.Literal["account_connection_openai"] = "account_connection_openai"

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
