# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from .phrase_based_action_trigger_config import PhraseBasedActionTriggerConfig
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class PhraseBasedActionTriggerInput(UniversalBaseModel):
    type: typing.Literal["action_trigger_phrase_based"] = "action_trigger_phrase_based"
    config: PhraseBasedActionTriggerConfig

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
