# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions

from ..core.datetime_utils import serialize_datetime
from .pinecone_vector_database_update_params_api_environment import PineconeVectorDatabaseUpdateParamsApiEnvironment
from .pinecone_vector_database_update_params_api_key import PineconeVectorDatabaseUpdateParamsApiKey
from .pinecone_vector_database_update_params_index import PineconeVectorDatabaseUpdateParamsIndex


class PineconeVectorDatabaseUpdateParams(pydantic.BaseModel):
    type: typing_extensions.Literal["vector_database_pinecone"]
    index: typing.Optional[PineconeVectorDatabaseUpdateParamsIndex]
    api_key: typing.Optional[PineconeVectorDatabaseUpdateParamsApiKey]
    api_environment: typing.Optional[PineconeVectorDatabaseUpdateParamsApiEnvironment]

    def json(self, **kwargs: typing.Any) -> str:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().json(**kwargs_with_defaults)

    def dict(self, **kwargs: typing.Any) -> typing.Dict[str, typing.Any]:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().dict(**kwargs_with_defaults)

    class Config:
        frozen = True
        smart_union = True
        json_encoders = {dt.datetime: serialize_datetime}
