# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class PlanType(str, enum.Enum):
    """
    An enumeration.
    """

    FREE = "free"
    DEVELOPER = "developer"
    ENTERPRISE = "enterprise"

    def visit(
        self,
        free: typing.Callable[[], T_Result],
        developer: typing.Callable[[], T_Result],
        enterprise: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is PlanType.FREE:
            return free()
        if self is PlanType.DEVELOPER:
            return developer()
        if self is PlanType.ENTERPRISE:
            return enterprise()
