# This file was auto-generated by Fern from our API Definition.

import typing
from .undefined import Undefined

PlayHtVoiceUpdateParamsVersion = typing.Union[typing.Literal["1"], typing.Literal["2"], Undefined]
