# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions

from .undefined import Undefined

PlayHtVoiceUpdateParamsQuality = typing.Union[
    typing_extensions.Literal["faster"],
    typing_extensions.Literal["draft"],
    typing_extensions.Literal["low"],
    typing_extensions.Literal["medium"],
    typing_extensions.Literal["high"],
    typing_extensions.Literal["premium"],
    Undefined,
]
