# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class PlayHtVoiceParamsVersion(str, enum.Enum):
    ONE = "1"
    TWO = "2"

    def visit(self, one: typing.Callable[[], T_Result], two: typing.Callable[[], T_Result]) -> T_Result:
        if self is PlayHtVoiceParamsVersion.ONE:
            return one()
        if self is PlayHtVoiceParamsVersion.TWO:
            return two()
