# This file was auto-generated by Fern from our API Definition.

import typing
from .undefined import Undefined

PlayHtVoiceUpdateParamsQuality = typing.Union[
    typing.Literal["faster"],
    typing.Literal["draft"],
    typing.Literal["low"],
    typing.Literal["medium"],
    typing.Literal["high"],
    typing.Literal["premium"],
    Undefined,
]
