# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ..core.datetime_utils import serialize_datetime
from .play_ht_voice_quality import PlayHtVoiceQuality
from .play_ht_voice_version import PlayHtVoiceVersion

try:
    import pydantic.v1 as pydantic  # type: ignore
except ImportError:
    import pydantic  # type: ignore


class PlayHtVoice(pydantic.BaseModel):
    id: str
    user_id: str
    voice_id: str
    api_user_id: typing.Optional[str]
    api_key: typing.Optional[str]
    version: typing.Optional[PlayHtVoiceVersion]
    speed: typing.Optional[float]
    quality: typing.Optional[PlayHtVoiceQuality]
    temperature: typing.Optional[float]

    def json(self, **kwargs: typing.Any) -> str:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().json(**kwargs_with_defaults)

    def dict(self, **kwargs: typing.Any) -> typing.Dict[str, typing.Any]:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().dict(**kwargs_with_defaults)

    class Config:
        frozen = True
        smart_union = True
        json_encoders = {dt.datetime: serialize_datetime}
