# This file was auto-generated by Fern from our API Definition.

import typing

PlayHtVoiceParamsQuality = typing.Union[
    typing.Literal["faster", "draft", "low", "medium", "high", "premium"], typing.Any
]
