# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ..core.datetime_utils import serialize_datetime
from .prompt_update_params_collect_fields import PromptUpdateParamsCollectFields
from .prompt_update_params_content import PromptUpdateParamsContent
from .prompt_update_params_context_endpoint import PromptUpdateParamsContextEndpoint
from .prompt_update_params_prompt_template import PromptUpdateParamsPromptTemplate

try:
    import pydantic.v1 as pydantic  # type: ignore
except ImportError:
    import pydantic  # type: ignore


class PromptUpdateParams(pydantic.BaseModel):
    content: typing.Optional[PromptUpdateParamsContent]
    collect_fields: typing.Optional[PromptUpdateParamsCollectFields]
    context_endpoint: typing.Optional[PromptUpdateParamsContextEndpoint]
    prompt_template: typing.Optional[PromptUpdateParamsPromptTemplate]

    def json(self, **kwargs: typing.Any) -> str:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().json(**kwargs_with_defaults)

    def dict(self, **kwargs: typing.Any) -> typing.Dict[str, typing.Any]:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().dict(**kwargs_with_defaults)

    class Config:
        frozen = True
        smart_union = True
        json_encoders = {dt.datetime: serialize_datetime}
