# This file was auto-generated by Fern from our API Definition.

import typing

from .collect_field import CollectField
from .undefined import Undefined

PromptUpdateParamsCollectFields = typing.Union[typing.List[CollectField], Undefined]
