# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from .rime_voice_model_id import RimeVoiceModelId
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class RimeVoice(UniversalBaseModel):
    id: str
    user_id: str
    type: typing.Literal["voice_rime"] = "voice_rime"
    speaker: str
    speed_alpha: typing.Optional[float] = None
    model_id: typing.Optional[RimeVoiceModelId] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
