# This file was auto-generated by Fern from our API Definition.

import typing

import typing_extensions

from .undefined import Undefined

RimeVoiceModelId = typing.Union[typing_extensions.Literal["mist"], typing_extensions.Literal["v1"], Undefined]
