# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from .rime_voice_update_params_speaker import RimeVoiceUpdateParamsSpeaker
from .rime_voice_update_params_speed_alpha import RimeVoiceUpdateParamsSpeedAlpha
from .rime_voice_update_params_model_id import RimeVoiceUpdateParamsModelId
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class RimeVoiceUpdateParams(UniversalBaseModel):
    type: typing.Literal["voice_rime"] = "voice_rime"
    speaker: typing.Optional[RimeVoiceUpdateParamsSpeaker] = None
    speed_alpha: typing.Optional[RimeVoiceUpdateParamsSpeedAlpha] = None
    model_id: typing.Optional[RimeVoiceUpdateParamsModelId] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
