# This file was auto-generated by Fern from our API Definition.

import typing
from .undefined import Undefined

RimeVoiceParamsModelId = typing.Union[typing.Literal["mist"], typing.Literal["v1"], Undefined]
