# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing
import typing_extensions

import pydantic

from ..core.datetime_utils import serialize_datetime
from .set_hold_action_update_params_action_trigger import SetHoldActionUpdateParamsActionTrigger
from .set_hold_action_update_params_config import SetHoldActionUpdateParamsConfig


class SetHoldActionUpdateParams(pydantic.BaseModel):
    type: typing_extensions.Literal["action_set_hold"]
    config: typing.Optional[SetHoldActionUpdateParamsConfig]
    action_trigger: typing.Optional[SetHoldActionUpdateParamsActionTrigger]

    def json(self, **kwargs: typing.Any) -> str:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().json(**kwargs_with_defaults)

    def dict(self, **kwargs: typing.Any) -> typing.Dict[str, typing.Any]:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().dict(**kwargs_with_defaults)

    class Config:
        frozen = True
        smart_union = True
        json_encoders = {dt.datetime: serialize_datetime}
