# This file was auto-generated by Fern from our API Definition.

import typing

from .set_hold_action_update_params_action_trigger_zero import SetHoldActionUpdateParamsActionTriggerZero
from .undefined import Undefined

SetHoldActionUpdateParamsActionTrigger = typing.Union[SetHoldActionUpdateParamsActionTriggerZero, Undefined]
