# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from .set_hold_action_update_params_config import SetHoldActionUpdateParamsConfig
from .set_hold_action_update_params_action_trigger import SetHoldActionUpdateParamsActionTrigger
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class SetHoldActionUpdateParams(UniversalBaseModel):
    type: typing.Literal["action_set_hold"] = "action_set_hold"
    config: typing.Optional[SetHoldActionUpdateParamsConfig] = None
    action_trigger: typing.Optional[SetHoldActionUpdateParamsActionTrigger] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
