# This file was auto-generated by Fern from our API Definition.

import typing

from .transfer_call_config import TransferCallConfig
from .undefined import Undefined

TransferCallActionUpdateParamsConfig = typing.Union[TransferCallConfig, Undefined]
