# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from .transfer_call_config import TransferCallConfig
from .transfer_call_action_action_trigger import TransferCallActionActionTrigger
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class TransferCallAction(UniversalBaseModel):
    id: str
    user_id: str
    type: typing.Literal["action_transfer_call"] = "action_transfer_call"
    config: TransferCallConfig
    action_trigger: typing.Optional[TransferCallActionActionTrigger] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
