# This file was auto-generated by Fern from our API Definition.

import typing

from .transfer_call_action_update_params_action_trigger_zero import TransferCallActionUpdateParamsActionTriggerZero
from .undefined import Undefined

TransferCallActionUpdateParamsActionTrigger = typing.Union[TransferCallActionUpdateParamsActionTriggerZero, Undefined]
