# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
from .twilio_credentials import TwilioCredentials
import typing
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class TwilioAccountConnection(UniversalBaseModel):
    id: str
    user_id: str
    credentials: TwilioCredentials
    type: typing.Literal["account_connection_twilio"] = "account_connection_twilio"
    steering_pool: typing.Optional[typing.List[str]] = None
    account_supports_any_caller_id: typing.Optional[bool] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
