# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from .twilio_account_connection_update_params_credentials import TwilioAccountConnectionUpdateParamsCredentials
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class TwilioAccountConnectionUpdateParams(UniversalBaseModel):
    credentials: typing.Optional[TwilioAccountConnectionUpdateParamsCredentials] = None
    type: typing.Literal["account_connection_twilio"] = "account_connection_twilio"

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
