# This file was auto-generated by Fern from our API Definition.

import typing

from .dtmf_action import DtmfAction
from .end_conversation_action import EndConversationAction
from .transfer_call_action import TransferCallAction

UpdateActionResponse = typing.Union[TransferCallAction, EndConversationAction, DtmfAction]
