# This file was auto-generated by Fern from our API Definition.

import typing

from .dtmf_action_update_params import DtmfActionUpdateParams
from .end_conversation_action_update_params import EndConversationActionUpdateParams

UpdateActionRequestBody = typing.Union[EndConversationActionUpdateParams, DtmfActionUpdateParams]
