# This file was auto-generated by Fern from our API Definition.

import typing
from .azure_voice import AzureVoice
from .eleven_labs_voice import ElevenLabsVoice
from .play_ht_voice import PlayHtVoice
from .rime_voice import RimeVoice
from .vocode_voice import VocodeVoice

VoicePageItemsItem = typing.Union[AzureVoice, ElevenLabsVoice, PlayHtVoice, RimeVoice, VocodeVoice]
