# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import typing_extensions

from .azure_voice_update_params import AzureVoiceUpdateParams
from .eleven_labs_voice_update_params import ElevenLabsVoiceUpdateParams
from .play_ht_voice_update_params import PlayHtVoiceUpdateParams
from .rime_voice_update_params import RimeVoiceUpdateParams


class VoiceUpdateParamsRequest_VoiceAzure(AzureVoiceUpdateParams):
    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class VoiceUpdateParamsRequest_VoiceRime(RimeVoiceUpdateParams):
    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class VoiceUpdateParamsRequest_VoiceElevenLabs(ElevenLabsVoiceUpdateParams):
    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


class VoiceUpdateParamsRequest_VoicePlayHt(PlayHtVoiceUpdateParams):
    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True


VoiceUpdateParamsRequest = typing.Union[
    AzureVoiceUpdateParams,
    RimeVoiceUpdateParams,
    ElevenLabsVoiceUpdateParams,
    PlayHtVoiceUpdateParams,
]
