# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from .event_type import EventType
from .http_method import HttpMethod
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class WebhookParams(UniversalBaseModel):
    subscriptions: typing.List[EventType]
    url: str
    method: typing.Optional[HttpMethod] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
