# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ..core.datetime_utils import serialize_datetime
from .webhook_update_params_method import WebhookUpdateParamsMethod
from .webhook_update_params_subscriptions import WebhookUpdateParamsSubscriptions
from .webhook_update_params_url import WebhookUpdateParamsUrl

try:
    import pydantic.v1 as pydantic  # type: ignore
except ImportError:
    import pydantic  # type: ignore


class WebhookUpdateParams(pydantic.BaseModel):
    subscriptions: typing.Optional[WebhookUpdateParamsSubscriptions]
    url: typing.Optional[WebhookUpdateParamsUrl]
    method: typing.Optional[WebhookUpdateParamsMethod]

    def json(self, **kwargs: typing.Any) -> str:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().json(**kwargs_with_defaults)

    def dict(self, **kwargs: typing.Any) -> typing.Dict[str, typing.Any]:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().dict(**kwargs_with_defaults)

    class Config:
        frozen = True
        smart_union = True
        json_encoders = {dt.datetime: serialize_datetime}
