# This file was auto-generated by Fern from our API Definition.

import typing

from .event_type import EventType
from .undefined import Undefined

WebhookUpdateParamsSubscriptions = typing.Union[typing.List[EventType], Undefined]
