# This file was auto-generated by Fern from our API Definition.

import typing

from ....types.pinecone_vector_database_params import PineconeVectorDatabaseParams

AgentParamsVectorDatabase = typing.Union[str, PineconeVectorDatabaseParams]
