# This file was auto-generated by Fern from our API Definition.

import typing

from ....types.undefined import Undefined

UpdateNumberRequestExampleContext = typing.Union[typing.Dict[str, str], Undefined]
