# This file was auto-generated by Fern from our API Definition.

import typing

from ....types.agent_update_params import AgentUpdateParams
from ....types.undefined import Undefined

UpdateNumberRequestInboundAgent = typing.Union[str, AgentUpdateParams, Undefined]
